'use strict';mix_d("VSESpotlightCards__vse-multi-video-card-desktop:vse-multi-video-card-desktop__7CHffA43","exports tslib @p/A @c/logger @c/metrics @c/scoped-dom @p/a-modal @c/aui-untrusted-ajax @c/navigation".split(" "),function(K,B,V,W,L,X,Y,Z,aa){function p(c){return c&&"object"===typeof c&&"default"in c?c:{"default":c}}var a=p(V),ba=p(W),x=p(X),ca=p(Y),da=p(Z),M={fiveColumn:"_vse-multi-video-card-desktop_style_fiveColumn__U4qm5",vseFeedCarousel:"_vse-multi-video-card-desktop_style_vseFeedCarousel__1JH03",
vseVideoWidgetContainer:"_vse-multi-video-card-desktop_style_vseVideoWidgetContainer__br1yo",vseFeedCarouselViewport:"_vse-multi-video-card-desktop_style_vseFeedCarouselViewport__3GRaW",spotlightFeedCarouselCard:"_vse-multi-video-card-desktop_style_spotlight-feed-carousel-card__57oDV",vseFeedCarouselCard:"_vse-multi-video-card-desktop_style_vseFeedCarouselCard__3vBMn",vseFeedCarouselControl:"_vse-multi-video-card-desktop_style_vseFeedCarouselControl__A5iL1",vseFeedCarouselControlLeft:"_vse-multi-video-card-desktop_style_vseFeedCarouselControlLeft__2sSlm",
vseFeedCarouselControlRight:"_vse-multi-video-card-desktop_style_vseFeedCarouselControlRight__ACMa7",vseFeedArrowRight:"_vse-multi-video-card-desktop_style_vseFeedArrowRight__35S1g",vseFeedArrowLeft:"_vse-multi-video-card-desktop_style_vseFeedArrowLeft__2Y0WT",vseFeedScrollbar:"_vse-multi-video-card-desktop_style_vseFeedScrollbar__2z6zN",vseFeedScrollbarTrack:"_vse-multi-video-card-desktop_style_vseFeedScrollbarTrack__2G_Ky",vseFeedScrollbarThumb:"_vse-multi-video-card-desktop_style_vseFeedScrollbarThumb__e2rem",
vseFeedCarouselScrollbar:"_vse-multi-video-card-desktop_style_vseFeedCarouselScrollbar__90X1j",vseFeedCarouselShelf:"_vse-multi-video-card-desktop_style_vseFeedCarouselShelf__3pIOr",vseSeeMoreLink:"_vse-multi-video-card-desktop_style_vseSeeMoreLink__1sX_Z",vseVideoWidgetHeaderBlock:"_vse-multi-video-card-desktop_style_vseVideoWidgetHeaderBlock__1qLH1",vseVideoWidgetHeader:"_vse-multi-video-card-desktop_style_vseVideoWidgetHeader__3mDBX",vseWidgetPageState:"_vse-multi-video-card-desktop_style_vseWidgetPageState__1UCt2",
vseVideoWidgetTitleText:"_vse-multi-video-card-desktop_style_vseVideoWidgetTitleText__2sQCp",vseCarouselItem:"_vse-multi-video-card-desktop_style_vseCarouselItem__Ddzmm",vseVideoImageWrapper:"_vse-multi-video-card-desktop_style_vseVideoImageWrapper__2ZCX7",vseProfilePlaceholder:"_vse-multi-video-card-desktop_style_vseProfilePlaceholder__2MIa-",vseVideoThumbnailProfile:"_vse-multi-video-card-desktop_style_vseVideoThumbnailProfile__ecyw8",vseWidgetLbVideoBlock:"_vse-multi-video-card-desktop_style_vseWidgetLbVideoBlock__2S1On",
vseWidgetLbVideoBlockWrapper:"_vse-multi-video-card-desktop_style_vseWidgetLbVideoBlockWrapper__3Fvaj",vseWidgetLbSpinner:"_vse-multi-video-card-desktop_style_vseWidgetLbSpinner__1KyPR",vseWidgetLbAbsolute:"_vse-multi-video-card-desktop_style_vseWidgetLbAbsolute__2SUcn",vseWidgetPopoverContainer:"_vse-multi-video-card-desktop_style_vseWidgetPopoverContainer__3Oy-b",vseNoRightPadding:"_vse-multi-video-card-desktop_style_vseNoRightPadding__aZWRa",vsePlaceholderLeft:"_vse-multi-video-card-desktop_style_vsePlaceholderLeft__UipPl",
vsePlaceholderRight:"_vse-multi-video-card-desktop_style_vsePlaceholderRight__uAiME",vsePlaceholder:"_vse-multi-video-card-desktop_style_vsePlaceholder__2p1SX",vseVerticalLightbox:"_vse-multi-video-card-desktop_style_vseVerticalLightbox__YJaIH",vseRemoveAbsolute:"_vse-multi-video-card-desktop_style_vseRemoveAbsolute__1KDpw"},r=function(c){c=JSON.stringify(c).replace(/\\\\/g,"");L.event(JSON.parse(c),"vsemetrics_widgetcards","vse.VSECardsEvents.5",{ssd:!1})},ea=function(c){return function(b){return a["default"].$.extend({eventSource:c.eventSource,
placementContext:c.placementContext,clientId:c.clientId,timestamp:new Date,userAgentData:navigator.userAgent,titleSessionId:"0",videoAsin:"",videoAsinList:c.videoAsinList||"",creativeId:""},b)}},b={pageType:"",clientPrefix:"",deviceType:"",placement:"",metricsPlacement:"",cardId:"",buildCsmPayload:function(c){}},m=function(c,a){void 0===a&&(a=1);try{L.count("spotlight:csm:"+b.clientPrefix+":"+c,a)}catch(f){y("failed to post CSM metric","ERROR")}},t=function(a,d){void 0===d&&(d=1);m(a+":"+b.deviceType,
d)},y=function(a,d){ba["default"].log("VSESpotlightCards: "+a+". Client prefix: "+b.clientPrefix+", Page type: "+b.pageType,d,"VSESpotlightCards")},N=function(c,d,f){try{if(a["default"].$("."+b.cardId).length){var g=!1,e=d.map(function(a){return a.contentId}).join(","),n=b.buildCsmPayload({eventName:b.clientPrefix+":cardWidgetRendered",intPayload:1,videoAsinList:e});r(n);m("cardWidgetRendered",1);var l=function(){for(var c=f.carouselItemClassName,g=0;g<d.length;g++)if(!d[g].impressionRecorded){var e=
a["default"].$("."+b.cardId+" ."+c+":nth-child("+(g+1)+")");if(a["default"].onScreen(e,0))e=b.buildCsmPayload({eventName:b.clientPrefix+":thumbnailImpression",intPayload:g,videoAsin:d[g].contentId}),r(e),d[g].impressionRecorded=!0;else break}},h=function(){if(g)a["default"].off(a["default"].constants.BROWSER_EVENTS.SCROLL,h);else{var d=b.buildCsmPayload({eventName:b.clientPrefix+":cardWidgetScrolledInView",intPayload:1,videoAsinList:e}),k=a["default"].$("."+b.cardId+" ."+f.carouselItemClassName).first();
k&&a["default"].onScreen(k,0)&&(r(d),d=a["default"].now()-c,m("cardWidgetScrolledInViewTime",d),t("cardWidgetScrolledInView"),g=!0,l())}};h();a["default"].on(a["default"].constants.BROWSER_EVENTS.SCROLL,h);f.widgetMetricsHandler(l,function(a){var c=b.buildCsmPayload({eventName:b.clientPrefix+":"+a+":paginationButtonClicked",intPayload:1});m(a+":paginationButtonClicked",1);r(c)})}}catch(fa){y("Error occurred while emitting widget metrics "+fa,"ERROR"),m("widgetMetricsEmissionError")}},F=function(a,
b,f,g,e){void 0===e&&(e=3);e--;da["default"].post(a,{accepts:"*/*",contentType:"application/json;charset=UTF-8",timeout:3E3},b).then(function(a){f(a)}).catch(function(c){0<e?F(a,b,f,g,e):g(c)})},ha=function(a,b){a="/gp/mobile/tag/?ref=vse_spotlight"+a+b.replace("/?_encoding=UTF8","");F(a,{},function(){},function(){})},O={},q,u,C=!1,D,P,G,v,l,w,H=!1,z,E,I="",ka=function(c,d,f,g){return B.__awaiter(void 0,void 0,void 0,function(){var e,n;return B.__generator(this,function(r){try{w=f;l=d;v=c;b.deviceType=
v?"Mobile":"Desktop";e=a["default"].now();n=x["default"].cardRoot.getElementsByClassName("spotlight-video-data-item");if(!n)return m("noCardsIngressDom"),A(),[2];if((D=x["default"].cardRoot.getElementsByClassName(l.vseWidgetPageState))&&D[0]&&D[0].dataset){u=D[0].dataset;q=Q(n,u);b.pageType="Spotlight";b.clientPrefix=b.pageType.toLowerCase();b.placement=(u.client||"Spotlight")+"Card-"+b.deviceType;b.metricsPlacement=(a["default"].capabilities.mobile?a["default"].capabilities.isAmazonApp?"mobile_app":
"mobile_web":a["default"].capabilities.tablet?a["default"].capabilities.isAmazonApp?"tablet_app":"tablet_web":"desktop_web")+"."+b.placement+".vse_spotlight";b.cardId=u.cardId;E="spotlight-component-feed-carousel-"+b.cardId;if(!a["default"].capabilities.video)return m("videoNotSupported"),[2];t("cardWidgetRendered");b.buildCsmPayload=ea({placementContext:b.metricsPlacement,clientId:"VSE",eventSource:"VSEWidgetCards",stringPayload:""});v?N(e,q,g):(a["default"].$("."+b.cardId+" ."+l.vsePlaceholder+
" .a-fixed-right-grid-inner").addClass(l.vseNoRightPadding),ia(n,u,e,g),a["default"].trigger("spotlight-card-ready-"+E));ja(n,u)}else m("pageStateNotFound"),A()}catch(h){y("fatal exception has occurred. Exception details: "+h,"FATAL"),m("widgetFatalException"),A()}return[2]})})},ia=function(b,d,f,g){try{a["default"].off("spotlight-carousel-items-added-"+E),a["default"].on("spotlight-carousel-items-added-"+E,function(){C||(C=!0,q=R(d),N(f,q,g))})}catch(e){J(e,b,void 0)}},R=function(a){var b=x["default"].cardRoot.getElementsByClassName("spotlight-video-data-item");
return Q(b,a)},la=function(c,d,f){O={requester:"VSEWidgetCards",clientPrefix:b.clientPrefix,page:b.pageType,placement:b.placement,device:b.deviceType,metadata:{id:"vse-video-widget-card",celQueryStringParam:c.celQueryStringParam},videoDataList:q,video:{contentID:d.contentId,contentIDType:"physicalID",videoURL:d.videoUrl,imageURL:d.imageUrl,videoTitle:d.title},marketplaceID:c.marketplaceId,locale:c.locale};F(aa.getLocation().origin+"/vap/ew/componentbuilder",O,function(c){P=!0;m("preloadSuccess");
a["default"].$("#"+f.popoverDivId+" ."+l.vseWidgetLbVideoBlock).html(c.responseBody);a["default"].on(b.clientPrefix+":vse:player:registered",function(){G&&a["default"].trigger("vse:cards:"+b.clientPrefix+":componentbuilder:succeeded")})},function(c){t("preloadFailed");m("preloadFailed:"+c.statusCode);y("NilgiriService componentbuilder call has failed: "+c.statusCode,"FATAL");A();a["default"].trigger("vse:cards:"+b.clientPrefix+":componentbuilder:failed")})},A=function(){var a=x["default"].cardRoot.getElementsByClassName(l.vseSeeMoreLink)[0];
a&&a.classList&&a.classList.add("aok-hidden")},ja=function(c,d){var f;try{var g=JSON.parse(d.popoverConfigs);[].forEach.call(c,function(a){a.children[0].removeAttribute("target")});var e,n=0,p;S();a["default"].$("."+b.cardId+" .spotlight-cards-ingress-carousel").delegate(".spotlight-carousel-item","click",function(c){C||(q=R(u),C=!0);c.preventDefault();var h=a["default"].$(c.currentTarget);c=0>h.closest("li").index()?0:h.closest("li").index();var k=q[c];k.metadata&&(e={contentId:k.contentId,title:k.metadata.title,
referenceLinkTitle:k.metadata.title,videoUrl:k.metadata.videoURL,duration:k.metadata.formattedDuration,imageUrl:k.metadata.videoImageUrl,fallbackSearchQuery:k.metadata.fallbackSearchQuery,videoVoteContainer:{},refTag:"spotlight-ingress"+c,relatedProducts:k.metadata.relatedProductsAsins,seeMoreText:k.metadata.seeMoreText,seeMoreLink:k.metadata.seeMoreLink,index:c,$el:h},h=b.buildCsmPayload({eventName:b.clientPrefix+":cardWidgetClicked",intPayload:1,videoAsin:e.contentId}),t("cardWidgetClicked"),r(h),
ha(c,d.celQueryStringParam),v?a["default"].trigger("vse:cards:"+b.cardId+":secondary:view:open"):(f=ca["default"].get(a["default"].$("."+b.cardId+" #"+g.popoverTriggerId)),a["default"].objectIsEmpty(f)?m("lbNotFoundDesktop"):f.show()))});a["default"].on(b.clientPrefix+":vse:player:registered",function(){a["default"].$("#"+g.popoverDivId+" ."+l.vseWidgetLbVideoBlock).first().animate({opacity:1})});a["default"].on("vseSpotlightIngressClicked",function(a){I=a});a["default"].on("a:popover:afterShow:"+
g.popoverName,function(h){try{if("undefined"===typeof e||null===e)return n=0,null;a["default"].$(h.popover.$popover).addClass(h.popover.$popover.find("."+l.vseWidgetPopoverContainer).data("cssClass"));p=g.popoverDivId;if(""===I||I!==b.cardId)n=0,a["default"].trigger("vseSpotlightIngressClicked",b.cardId);n++;G=!0;if(1===n){a["default"].$(h.popover.$popover).addClass(l.vseVerticalLightbox);var m=a["default"].now();f&&f.refresh();la(d,e,g);a["default"].off("vse:cards:"+b.clientPrefix+":componentbuilder:succeeded");
a["default"].off("vse:cards:"+b.clientPrefix+":componentbuilder:failed");a["default"].on("vse:cards:"+b.clientPrefix+":componentbuilder:succeeded",function(){T(e,p,g);a["default"].$(h.popover.$popover).addClass(l.vseRemoveAbsolute);v&&""===e.relatedProducts&&""!==e.seeMoreLink&&""!==e.seeMoreText&&a["default"].trigger("vse:"+b.clientPrefix+":seeMoreBlock:init",e.seeMoreLink,e.seeMoreText);var c=a["default"].now()-m;t("cardWidgetPopoverContentWaitTime",c)});a["default"].on("vse:cards:"+b.clientPrefix+
":componentbuilder:failed",function(){U(c);f?f.hide():a["default"].trigger("vse:cards:"+b.cardId+":secondary:view:close");a["default"].delay(function(){var a=x["default"].createElement("a");a.setAttribute("href",e.fallbackSearchQuery);a.setAttribute("target","_black");a.click()},500)})}else T(e,p,g)}catch(k){J(k,c,f)}});a["default"].on("a:popover:beforeHide:"+g.popoverName,function(){G=!1;P?(a["default"].trigger("vse:"+b.clientPrefix+":page:lightBoxClosed"),null!=w&&z&&w.unsubscribe(z)):t("cardWidgetLBClosedBeforeAjax")});
a["default"].declarative("vse-widget-carousel-see-more","click touch",function(){v&&(H=!0);a["default"].$("."+b.cardId+" .spotlight-cards-ingress-carousel").find("."+l.vseCarouselItem).first().click();t("seeMoreLinkClicked");var c=b.buildCsmPayload({eventName:b.clientPrefix+":seeMoreLinkClicked",intPayload:1});r(c)})}catch(h){J(h,c,f)}},J=function(a,b,f){y("fatal exception has occurred in LB. Exception details: "+a,"FATAL");m("lightboxOpenFatalException");A();U(b);f&&f.hide()},U=function(a){S();[].forEach.call(a,
function(a,b){a.children&&a.children[0]&&a.children[0].setAttribute("target",q[b].metadata.fallbackSearchQuery)})},S=function(){a["default"].$("."+b.cardId+" .spotlight-cards-ingress-carousel").undelegate(".spotlight-carousel-item","click")},Q=function(a,b){var c=[];[].forEach.call(a,function(a,b){a=a.dataset;(b=a.asin)&&c.push({contentId:b,metadata:{id:a.id||"",videoImageUrl:a.videoImageUrlUnchanged||a.videoImageUrl||"",videoURL:a.videoUrl||a.videoURL||"",title:a.title||"",formattedDuration:a.formattedDuration||
"",relatedProductsAsins:a.relatedProductsAsins||"",fallbackSearchQuery:a.fallbackSearchQuery||"",seeMoreText:a.seeMoreText||"",seeMoreLink:a.seeMoreLink||""},impressionRecorded:!1})});return c},T=function(c,d,f){H&&a["default"].trigger("vse:"+b.clientPrefix+":page:watchAllClicked");H=!1;a["default"].trigger("vse:"+b.clientPrefix+":page:lightBoxOpened",{assetSpec:c,lightBoxId:d});0<a["default"].$("#"+f.popoverDivId+" ."+l.vseWidgetLbVideoBlock).length&&(z=a["default"].$("."+l.vseWidgetLbVideoBlock).get(0),
null!=w&&(ma(z),w.elect(z)))},ma=function(a){w.subscribe(a,function(a){},{buffer:0})};K._operationNames=[];K.card=function(){return B.__awaiter(void 0,void 0,void 0,function(){var c;return B.__generator(this,function(d){switch(d.label){case 0:return c={carouselItemClassName:M.vseFeedCarouselCard,widgetMetricsHandler:function(c,d){var e=a["default"].throttle(function(){c()},500,{leading:!1});a["default"].on(a["default"].constants.BROWSER_EVENTS.RESIZE,function(){c()});a["default"].$("."+b.cardId+" .spotlight-feed-carousel-control-left").click(function(){d("left");
e()});a["default"].$("."+b.cardId+" .spotlight-feed-carousel-control-right").click(function(){d("right");e()})}},[4,ka(!1,M,null,c)];case 1:return d.sent(),[2]}})})}});
