'use strict';mix_d("P13NSCCards__p13n-rvi:p13n-rvi__94r-UQsz","exports tslib @c/aui-carousel @c/dom @c/remote-operations @c/scoped-dom @p/A @p/a-carousel-framework @c/browser-operations @c/metrics @c/aui-modal @c/aui-untrusted-ajax @c/logger".split(" "),function(B,q,F,G,H,I,J,K,L,x,M,N,O){function r(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var P=r(F),Q=r(H),p=r(I),v=r(J),R=r(K),y=r(L),S=r(x),T=r(M),U=r(N),w=r(O),z=function(a){x.count(a,(x.count(a)||0)+1)},V=function(a){var d=
Array.prototype.slice.call(a.querySelectorAll("[data-metrics]"));d.push(a);d.forEach(function(b){if(b&&b.dataset&&b.dataset.metrics){var c=JSON.parse(b.dataset.metrics),e;for(e in c)c.hasOwnProperty(e)&&x.count(e,c[e]);b.removeAttribute("data-metrics")}})},W=function(){var a=p["default"].cardRoot.querySelector(".p13n-edit-your-recs-button"),d=p["default"].cardRoot.querySelector(".p13n-kebab-button-edit-recs-bottom-sheet");if(d&&a){var b=y["default"].setup();S["default"].count("mobile-carousel-card:p13nEditRecsBottomSheet:rendered",
1);b.define("show-sheet","click",function(){z("mobile-carousel-card:p13nEditRecsBottomSheet:show");z("mobile-carousel-card:internal:p13nEditRecsBottomSheet:show")});b.attach("show-sheet",d);a.addEventListener("click",function(){z("mobile-carousel-card:p13nEditRecsBottomSheet:notInterested")})}},Y=function(a){return q.__awaiter(void 0,void 0,void 0,function(){var d,b,c,e,g;return q.__generator(this,function(f){d=p["default"].cardRoot.querySelector(".report-problem-modal-root");if(!d)return[2];b={a11yOpenMessage:"A modal for internal users to report problems with recommendations",
hideHeader:!1,width:560};c=T["default"].create("report-flag-modal",".report-problem-modal-root",b);e=y["default"].setup();g=p["default"].cardRoot.querySelector(".report-flag");e.define("show","click",function(){c.show()});e.attach("show",g);X(a,c);return[2]})})},X=function(a,d){var b=p["default"].cardRoot.querySelector(".report-flag"),c=y["default"].setup();c.define("showFlag","mouseover",function(){b.classList.remove("report-flag-hide")});c.define("hideFlag","mouseout",function(){b.classList.add("report-flag-hide")});
c.attach("showFlag",a);c.attach("hideFlag",a);var e=p["default"].cardRoot.querySelector(".internal-flag-form");e.onsubmit=function(g){return Z(e,g,a)};v["default"].on("a:popover:hide:"+d.id,function(){e.reset();var g=e.querySelector(".internal-flag-form-end").nextSibling;g&&g.classList.contains("report-problem-message")&&(g.innerText="")})},Z=function(a,d,b){d.preventDefault();d=a.querySelector(".internal-flag-env-data").dataset;var c=a.querySelector(".internal-flag-title-text").value,e=a.querySelector(".internal-flag-description").firstElementChild.value,
g=a.querySelector(".internal-flag-alias").value,f=a.querySelector(".internal-flag-form-end");if(!(c&&c.trim()&&e&&e.trim()&&g&&g.trim()))return A(f,!1,"Something went wrong. One of the required fields was missing."),!1;a=p["default"].cardRoot.querySelectorAll(".a-carousel-card");b=aa(b,a.length);c="Internal user reported issue '"+c+"' with widget: "+p["default"].cardRoot.querySelector(".a-carousel-heading").innerText;d=ba(a,b,e,g,d);U["default"].post("https://p13ngoals.corp.amazon.com/sims",{accepts:"text/html, application/json",
contentType:"application/json;charset=UTF-8"},{sim_params:{assigned_folder:"9c9c97c9-6f69-4dba-a55d-26045c6a3068",description:d,descriptionContentType:"text/amz-markdown-sim",extensions:{tt:{assignedGroup:"P13N Report a Problem CX",category:"Website",impact:5,item:"Report a Problem CX",type:"Personalization"}},tags:[{id:"internal-problem-generated"}],title:c}}).then(function(k){A(f,!0,k)}).catch(function(k){A(f,!1,k)});return!1},aa=function(a,d){if(!a.dataset.aCarouselOptions)return w["default"].log("Empty ASIN List in carouselElement.dataset.aCarouselOptions",
"ERROR"),[];a=JSON.parse(a.dataset.aCarouselOptions).ajax.id_list;var b=p["default"].cardRoot.querySelector(".a-carousel-firstvisibleitem");b=(Number(b.value)||1)-1;return a.map(function(c){return JSON.parse(c).id}).slice(b,b+d)},ba=function(a,d,b,c,e){for(var g="",f=0;f<a.length;f++){var k=a[f].querySelector(".a-dynamic-image");g+=(k?"![]("+k.src+")":"IMAGE MISSING")+"\nASIN: "+(d[f]?d[f]:"ASIN MISSING")+"\n\n"}return"**This SIM-T ticket is created by the 'Report a Problem' internal tool. To know more, here's its wiki: https://w.amazon.com/bin/view/Personalization/CoreRecommendations/Projects/Canaries/Report-a-Problem-UX-on-P13NWidget/UserGuide/**\n\n**Alias:** ["+
(c+"](https://phonetool.amazon.com/users/"+c+")\n**Comment:** "+b+"\n\n**Widget Group ID:** "+e.widgetGroupId+"\n**Strategy ID:** "+e.strategyId+"\n**CTI:** "+e.cti+"\n**Facets:** ")+(e.facets+"\n**Content Reftag:** "+e.reftag+"\n"+(""!==e.baseAsin?"**Page ASIN:** "+e.baseAsin+"\n":"")+"\n**SessionID:** ")+(e.sessionId+"\n**MarketplaceID:** "+e.marketplaceId+"\n**Device Type:** "+e.deviceType+"\n\n**List of ASINs:**\n\n")+g},A=function(a,d,b){var c=a.nextSibling;c&&c.classList.contains("report-problem-message")||
(c=document.createElement("h5"),c.classList.add("report-problem-message"),a.after(c));d?(c.classList.remove("a-color-error"),b.responseBody&&"object"===typeof b.responseBody?b.responseBody.response&&b.responseBody.response.id?c.innerHTML="Success, here's the <a href=\"https://t.corp.amazon.com/"+b.responseBody.response.id+'" target="_blank">SIM-T ticket</a> you created.':(w["default"].log("Fail to find the id of the SIM-T ticket created in the response body of response data.","ERROR"),c.innerText=
"Success, but we could not find the link to the SIM-T ticket."):(w["default"].log("The response body of response data is not an object.","ERROR"),c.innerText="Success, but we could not find the link to the SIM-T ticket.")):(c.classList.add("a-color-error"),c.innerText="string"===typeof b?b:"Oops! Something went wrong. Please try again.")},C=/(?=[ \-\/])|(?=[\u3105-\u312F])|(?=[\u31A0-\u31BA])|(?=[\u4E00-\u9FD5])|(?=[\u3400-\u4DB5])|(?=[\uF900-\uFAFF])|(?=[\u3040-\u309F])|(?=[\u30A0-\u30FF])|(?=[\u3190-\u319F])/,
D=/[^\/\-\[\]():\s]/,ca=function(a){var d=v["default"].$("<div>")[0];d.classList.add("p13n-sc-offscreen-truncate");var b=parseInt(a.getAttribute("data-rows")||"2",10),c=function(){var f=a.innerHTML;a.innerHTML="&hellip;";var k=a.clientHeight;a.innerHTML=f;return k}();if(b){if(c){var e=function(f){d.innerHTML=f;return Math.round(d.clientHeight/c)<=b},g=function(f,k){f=f.split(k);var l=Math.floor(a.clientWidth/12),u=function(h){d.classList.add("p13n-sc-offscreen-truncate");d.style.overflow="hidden";
d.textContent=h;a.appendChild(d);h=a.clientWidth>=a.scrollWidth;a.removeChild(d);return h},n=function(h){var t=h.length-l;h.trim().length>l&&!u(h)&&Array.prototype.slice.call(h).map(function(m,E){return E>l&&E<=t&&D.test(m)?"&shy;"+m:m});return h};return f.map(function(h){return n(h)}).join("")};return{truncate:function(){var f=a.innerHTML.trim(),k=a.textContent||"";f=g(f,C);a.appendChild(d);if(e(f))a.removeChild(d),a.innerHTML=f;else{var l=f.split(C);for(var u=1,n=l.length,h,t,m=0;u!==n;)if(h=Math.floor((n+
u)/2),t=l.slice(0,h).join("")+"&hellip;",e(t)){if(1>=n-h){for(m=h;0<m&&!D.test(l[m-1]);)m--;break}u=h}else n=h;l=0===m?void 0:l.slice(0,m).join("")+"&hellip;";l?(a.innerHTML=l,a.setAttribute("title",k)):(w["default"].log("Unable to successfully truncate line "+f,"ERROR"),a.removeChild(d))}}}}w["default"].log("Truncation element does not have a line height or it is zero","ERROR")}else w["default"].log("Truncation element missing necessary line number data","ERROR")},da=function(a){var d=Array.prototype.slice.call(a.getElementsByClassName("p13n-sc-truncate"));
a=a.getElementsByClassName("p13n-sc-truncate-fallback");(window.CSS&&CSS.supports&&CSS.supports("-webkit-line-clamp","1")?d:d.concat(Array.prototype.slice.call(a))).filter(function(b){return!!b.offsetParent}).map(function(b){var c=ca(b);c&&(c.truncate(),b.classList.add("p13n-sc-truncated"),b.classList.remove("p13n-sc-truncate"),b.classList.remove("p13n-sc-truncate-fallback"),b.className=b.className.replace(/p13n-sc-line-clamp-\d/g,""))})},ea={initCarousel:function(a){return q.__awaiter(void 0,void 0,
void 0,function(){var d,b,c;return q.__generator(this,function(e){d=(a||{}).afterPageLoaded;b=p["default"].cardRoot.classList.contains("p13n-sc-shoveler")?[p["default"].cardRoot]:Array.prototype.slice.call(p["default"].cardRoot.getElementsByClassName("p13n-sc-shoveler"));c=Q["default"].setup(["getCarouselItems"]);if(null===b||void 0===b||!b.length)return[2];b.forEach(function(g){return q.__awaiter(void 0,void 0,void 0,function(){var f,k,l,u,n;return q.__generator(this,function(h){switch(h.label){case 0:f=
function(){v["default"].loadDynamicImage("[data-name]='"+n+"' .p13n-sc-dynamic-image");da(g);V(g);null===d||void 0===d?void 0:d(g)};f();if(g.classList.contains("p13n-carousel-initialized"))return[2];g.classList.add("p13n-carousel-initialized");k=R["default"].getCarousel(G.unscope(g));l=P["default"].getCarousel(g);u=g.dataset||{};n=k.getAttr("name");return[4,Promise.all([l.initialized,Y(g)])];case 1:return h.sent(),W(),v["default"].on("a:carousel:"+n+":change:pageSize",f),v["default"].on("a:carousel:"+
n+":change:loading",f),v["default"].on("a:carousel:"+n+":change:animating",f),v["default"].on("a:carousel:"+n+":change:fetchedItems",f),l.attachRemoteOperation(function(t){var m=t.indexes;t=t.ids;return c.getCarouselItems(q.__assign(q.__assign({},u),{ids:t,indexes:m,offset:String(m[0]||0)}))}),[2]}})})});return[2]})})}};B._operationNames=["getCarouselItems"];B.card=function(){return q.__awaiter(void 0,void 0,void 0,function(){return q.__generator(this,function(a){switch(a.label){case 0:return[4,ea.initCarousel()];
case 1:return a.sent(),[2]}})})}});
