/*
 *****************************************************************************
    Copyright (c) Microsoft Corporation.

    Permission to use, copy, modify, and/or distribute this software for any
    purpose with or without fee is hereby granted.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
    REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
    INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
    LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
    PERFORMANCE OF THIS SOFTWARE.
*****************************************************************************/
(function(O){var f=window.AmazonUIPageJS||window.P,L=f._namespace||f.attributeErrors,a=L?L("CardJsRuntimeBuzzCopyBuild",""):f;a.guardFatal?a.guardFatal(O)(a,window):a.execute(function(){O(a,window)})})(function(O,f,L){mix_d("@c/api-lock",["exports"],function(a){var c={},d=function(a){delete c[a.type]};a.default={isLockedFor:function(a){return!a.every(function(a){return!!c[a]})},unlockForEvent:function(a,b){c[a.type]=a;try{var e=b();if(e instanceof Promise)return e.finally?e.finally(function(){return d(a)}):
e.then(function(){return d(a)},function(b){d(a);throw b;});d(a)}catch(w){throw d(a),w;}return Promise.resolve()},unlockForEventOnce:function(a){c[a.type]=a},resetLocks:function(){Object.keys(c).forEach(function(a){return d(c[a])})}};a.initialize=function(a,b,c){};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-untrusted-ajax",["exports","tslib","@p/a-ajax","@c/guard"],function(a,c,d,e){function b(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function k(a){a=a&&a.http&&
a.http.getResponseHeader("Content-Type");if(!a)return"NO-CONTENT-TYPE-FOUND";a=a.split(",").map(function(a){return a.split(";")[0].trim()});return a.find(function(a){return"application/json"===a||"text/html"===a})||a[0]}function w(a,b){return{responseBody:b,contentType:k(a),xhr:a.http}}function f(a,b){return h["default"].promise(new Promise(function(d,e){var u=c.__assign(c.__assign({},b),{abort:function(){e("Ajax request aborted")},error:function(a,b){var c=a.http.status;200===c||202===c||204===c||
304===c?d(w(a,a.http.responseText)):(a=new r("Ajax request failed",a.http.status,b,a.http.status?L:"readyState: "+a.http.readyState+"."),e(a))},success:function(a,b,c){d(w(c,a))}});v["default"].ajax(a,u)}))}var v=b(d),h=b(e),m={contentType:"application/json"},r=function(a){function b(b,c,d,e){e=a.call(this,"["+c+" "+d+"] "+b+(e?". ":"")+(e||""))||this;e.responseMessage=b;e.statusCode=c;e.statusText=d;e.type="AjaxError";return e}c.__extends(b,a);return b}(Error);d=function(a,b,d){b=c.__assign(c.__assign({},
m),b);return f(a,{timeout:b.timeout,accepts:b.accepts,contentType:b.contentType,headers:b.additionalHeaders||{},params:d||{},paramsFormat:"json",method:"POST"})};e=function(a,b,d){b=c.__assign(c.__assign({},m),b);return f(a,{timeout:b.timeout,accepts:b.accepts,contentType:b.contentType,headers:b.additionalHeaders||{},params:d||{},method:"get",cache:!1})};var u={get:e,post:d};a.AjaxError=r;a.default=u;a.get=e;a.initialize=function(a,b,c){};a.post=d;Object.defineProperty(a,"__esModule",{value:!0})});
mix_d("@c/browser-operations","exports @c/guard @c/scoped-dom tslib @c/dom @c/api-lock @p/a-events @p/A @c/logger".split(" "),function(a,c,d,e,b,k,w,p,v){function h(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function m(a){return(a=a.getAttribute("data-mix-operations"))?a.trim():L}function r(a,b,g){q["default"].on(K[b],function(l){x["default"].unlockForEvent(l||{type:b},g.bind(null,{event:l,type:b,operationName:a,acknowledge:l&&l.acknowledge?function(){return l.acknowledge(document.body)}:
function(){},stopBubble:function(){throw Error("stopBubble not supported for global events");}}))})}function u(a){a.acknowledge=a.acknowledge||function(){};E.cards.filter(function(b){return b.ScopedDom.isAccessibleEvent(a)}).forEach(function(b){b.cardHandler(b.operations,b.ScopedDom.proxify(a),a)})}function C(a,g,c){var l=this,B=F(c).map(function(n){return I(A(n).map(function(b){return a[b]||[]})).filter(function(a){return a.eventType===c.type}).map(function(a){return function(){return e.__awaiter(l,
void 0,void 0,function(){var l,B=this;return e.__generator(this,function(d){switch(d.label){case 0:return l=!1,[4,x["default"].unlockForEvent(c,function(){return e.__awaiter(B,void 0,void 0,function(){var B;return e.__generator(this,function(d){switch(d.label){case 0:return d.trys.push([0,2,,3]),[4,a.callback({event:g,type:a.eventType,target:g.target,currentTarget:n,operationName:a.name,acknowledge:function(){return c.acknowledge(b.unscope(n))},stopBubble:function(){l=!0}})];case 1:return d.sent(),
[3,3];case 2:return B=d.sent(),y["default"].log(B),[3,3];case 3:return[2]}})})})];case 1:return d.sent(),[2,l]}})})}})});return I(B).reduce(function(a,b){return a.then(function(a){return a||b()})},Promise.resolve(!1))}function F(a){var b=a.target,c=[];if(a.eventPhase===Event.CAPTURING_PHASE)g(b)&&m(b)&&c.push(b);else for(;g(b);)m(b)&&c.push(b),b=b.parentElement;return c}function A(a){return(a=m(a))?a.split(/[\s,|]+/).reduce(function(a,b){0>a.indexOf(b)&&a.push(b);return a},[]):[]}function D(){return{define:function(a,
b,g){var c=z["default"].current(g);[].concat(b).forEach(function(b){J[b]?r(a,b,c):(t[a]=t[a]||[],t[a].push({name:a,eventType:b,callback:c}),0>E.listeners.indexOf(b)&&(document.addEventListener(b,u,!!H[b]),E.listeners.push(b)))})},attach:function(a,b){var g=b.getAttribute("data-mix-operations");g=g?g.split(" "):[];-1<g.indexOf(a)||g.push(a);b.setAttribute("data-mix-operations",g.join(" "))}}}var z=h(c),G=h(d),x=h(k),q=h(w);c=h(p);var y=h(v),E=f.mixBrowserOperationsState=f.mixBrowserOperationsState||
{listeners:[],cards:[]},H={focus:!0,blur:!0,mouseenter:!0,mouseleave:!0},J={orientationchange:!0,resize:!0,scroll:!0},K={orientationchange:c["default"].constants.BROWSER_EVENTS.ORIENTATION_CHANGE,resize:c["default"].constants.BROWSER_EVENTS.RESIZE,scroll:c["default"].constants.BROWSER_EVENTS.SCROLL},I=function(a){var b;switch(a.length){case 0:return a;case 1:return a[0];default:return(b=[]).concat.apply(b,e.__spread(a))}},g=function(a){return!!a&&a.nodeType===Node.ELEMENT_NODE&&G["default"].isAccessibleElement(a)},
t={};a.default={setup:D};a.initialize=function(a,b,g){E.cards.push({operations:t,cardHandler:C,ScopedDom:G["default"]})};a.setup=D;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/browser-window",["exports"],function(a){var c=function(){return{get devicePixelRatio(){return f.devicePixelRatio},get innerWidth(){return f.innerWidth},get innerHeight(){return f.innerHeight},get outerWidth(){return f.outerWidth},get outerHeight(){return f.outerHeight},get pageXOffset(){return f.pageXOffset},
get pageYOffset(){return f.pageYOffset},get screenX(){return f.screenX},get screenY(){return f.screenY},get scrollX(){return f.scrollX},get scrollY(){return f.scrollY}}},d=c();a.default=d;a.getWindow=c;a.initialize=function(a,b,c){};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@amzn/mix.client-runtime",["exports","tslib"],function(a,c){function d(a,b){void 0===b&&(b=function(a){});return setTimeout(function(){var c="Late loading module "+a;f.P.log(c,"WARN","MIX");b(c)},3E3)}function e(a){var b=
h,c=new Promise(function(a){b=a}),e=d(a);c.then(function(){return clearTimeout(e)});return{promise:c,resolve:b}}function b(a){v[a]||(v[a]=e(a));return v[a]}function k(a,d){return c.__awaiter(this,void 0,void 0,function(){function e(a){a in d||(d[a]=u(a));return d[a]}function u(a){return c.__awaiter(this,void 0,void 0,function(){var d,q,u,h,m;return c.__generator(this,function(c){switch(c.label){case 0:return[4,b(a).promise];case 1:return d=c.sent(),q=d.capabilities,m=u=d.cardModuleFactory,[4,Promise.all((q||
[]).map(e))];case 2:return h=m.apply(void 0,[c.sent()]),k.push(h),[2,h]}})})}var k,h;return c.__generator(this,function(b){switch(b.label){case 0:return k=[],[4,Promise.all(a.map(e))];case 1:return h=b.sent(),[2,{requestedOrder:h,initializationOrder:k}]}})})}function w(a,b){b="#"===b[0]?b.slice(1):b;if(b=document.getElementById(b))if(b.hasAttribute("data-mix-claimed"))a.log("Could not register card: Candidate root claimed","WARN","MIX");else return b.setAttribute("data-mix-claimed","true"),b;else a.log("Could not register card: Candidate root not found",
"WARN","MIX")}function p(a){a=a.getAttribute("data-model");if(!a)return L;try{return JSON.parse(a)}catch(C){throw Error("Unable to inflate seed ViewModel: "+C);}}var v={},h=function(){},m=function(a,b,c,d){return function(e){var h=b();e.filter(function(a){return a.initialize}).forEach(function(b){b.initialized||(b.initialize(a,h,c,d),b.initialized=!0);return b})}},r=function(a,b,d,e,h){void 0===h&&(h={});return c.__awaiter(void 0,void 0,void 0,function(){var m,u,w,q,v,f,r,J,K,I,g;return c.__generator(this,
function(t){switch(t.label){case 0:return[4,k(null!==(I=b.capabilities)&&void 0!==I?I:[],e)];case 1:return m=t.sent(),u=m.initializationOrder,w=m.requestedOrder,v=[],0!==a.indexOf("@")?[3,3]:[4,k([a],e)];case 2:return f=t.sent(),r=c.__read(f.requestedOrder,1),J=r[0],K=f.initializationOrder,q=J,v=K,[3,4];case 3:q=null!==(g=h[a])&&void 0!==g?g:h[a]=b.cardModuleFactory(w,d),t.label=4;case 4:return[2,{resolvedMod:q,capabilitiesToInitialize:c.__spread(v,u)}]}})})};a.registerCapabilityModule=function(a,
c){b(a).resolve(c)};a.registerCardFactory=function(a,b){return c.__awaiter(this,void 0,void 0,function(){var e,h,k,v,u,x,q,y,E,C,J=this;return c.__generator(this,function(K){switch(K.label){case 0:e={};if(h=b.require)v={},k=function(a,b,t){var g=d(a[0],function(){});h(a,function(d){return c.__awaiter(J,void 0,void 0,function(){var l,J,K,n,h;return c.__generator(this,function(B){switch(B.label){case 0:clearTimeout(g);l=a[0];if(!d.cardModuleFactory)return[3,5];B.label=1;case 1:return B.trys.push([1,
3,,4]),[4,r(l,d,k,e,v)];case 2:return J=B.sent(),K=J.resolvedMod,n=J.capabilitiesToInitialize,C(c.__spread([K],n)),b(K),[3,4];case 3:return h=B.sent(),t(h),[3,4];case 4:return[3,6];case 5:b(d),B.label=6;case 6:return[2]}})})},t)};return[4,r(a,b,k,e)];case 1:return u=K.sent(),x=u.resolvedMod,q=u.capabilitiesToInitialize,y=x.P,C=m(a,function(){return E},x,y),[2,new Promise(function(b,g){y.execute(function(){var c=w(y,a);c?(E=p(c),C(q),f.mixCardInitTimeouts&&clearTimeout(f.mixCardInitTimeouts[a]),(c=
x.card(E))&&c.then?c.then(function(){b()}).catch(function(a){y.log(a.message,"FATAL");g(a)}):b()):(f.mixCardInitTimeouts&&clearTimeout(f.mixCardInitTimeouts[a]),b())})})]}})})};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/csa",["exports","tslib"],function(a,c){a.callEventInstance=function(a,e){for(var b=[],d=2;d<arguments.length;d++)b[d-2]=arguments[d];(d=f.mix_csa_event)&&d(a).apply(void 0,c.__spread([e],b))};a.initialize=function(a,c,b){};Object.defineProperty(a,"__esModule",{value:!0})});
mix_d("@c/dom",["exports"],function(a){var c,d,e=[],b=function(a){return document.createElement(a)},k={createElement:b,get cardRoot(){return d},get container(){return c},get scopes(){return e}};a.cardRoot=function(){return d};a.container=function(){return c};a.createElement=b;a.default=k;a.initialize=function(a,b,k){a="#"===a[0]?a.slice(1):a;d=document.getElementById(a);if(!d)throw Error("No node found for dom initialization");c=d.parentNode;e=[d]};a.scopes=function(){return e};a.unscope=function(a){return a&&
a.__unscope__?a.__unscope__(k):a};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/guard",["exports","@c/logger"],function(a,c){var d=c&&"object"===typeof c&&"default"in c?c:{"default":c},e;c=function(a,b){return e.guardFatal(a,b)};var b=function(a,b){return e.guardError(a,b)},k=function(a){return e.guardCurrent(a)},f=function(a){return a.catch(function(a){d["default"].log(a.message);throw a;})},p={asFatal:c,asError:b,current:k,promise:f};a.asError=b;a.asFatal=c;a.current=k;a.default=
p;a.initialize=function(a,b,c,d){e=d};a.promise=f;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/logger",["exports"],function(a){var c,d=function(a,b,d){return a.message?c.logError(a,null,b,d):c.log(a,b,d)};a.default={log:d};a.initialize=function(a,b,d,f){c=f};a.log=d;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/metrics",["exports"],function(a){var c,d=function(a,b,c){return f.ue.count(a,b,c)},e=function(a,b,c,d){f.ue.event(a,b,c,d)},b=function(a,b,c,d){f.uet(a,b,c,d)},
k=function(a,b,c){f.uex(a,b,c)},w=function(){return w},p={count:d,event:e,uet:b,uex:k,get rid(){return c}};a.count=d;a.default=p;a.event=e;a.initialize=function(a,b,d){c=f.ue.rid};a.rid=w;a.uet=b;a.uex=k;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/navigation",["exports"],function(a){var c=function(a){f.location.assign(a)},d=function(){return{get hash(){return f.location.hash},get host(){return f.location.host},get hostname(){return f.location.hostname},get href(){return f.location.href},
get origin(){return f.location.origin},get pathname(){return f.location.pathname},get port(){return f.location.port},get protocol(){return f.location.protocol},get search(){return f.location.search}}};a.default={setLocation:c,getLocation:d};a.getLocation=d;a.initialize=function(a,b,c){};a.setLocation=c;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/remote-operations","exports @c/dom @c/aui-untrusted-ajax @c/guard @c/metrics @c/scoped-dom @c/scoped-metrics tslib".split(" "),function(a,
c,d,e,b,k,w,p){function v(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function h(a){var b=function(c){var d=b.trackingApplicable,B=b.trackingParams,e=b.trackingStandalone,M="\x3d"===g[g.length-1],q=g+a;if(l!==L){e&&(q=M?q+"\x26track\x3dtrue":q+"/track");if(d){d=l;B=B||{};var h=B.refSuffix,I=B.ref_;B=p.__rest(B,["refSuffix","ref_"]);e=d.ref_||"";I=I||"";h=h||"";var k=e;I?k=I:h&&(I=e.match(E)||h.match(H),k=[e,h].join(I?"":"_"));e=(e=k)?{ref_:e}:{};d=p.__assign(p.__assign(p.__assign(p.__assign(p.__assign({},
K),d),B),e),J)}else d=l;d=d||{};B=[];for(var f in d)d.hasOwnProperty(f)&&(e=d[f],B.push(encodeURIComponent(f)+"\x3d"+encodeURIComponent(e)));q+=(M?"\x26":"?")+B.join("\x26")}return x(q,a,c,t)};b.factoryClone=function(b){var c=h(a);b&&(c.trackingParams=b.trackingParams||{},c.trackingStandalone=b.trackingStandalone,c.trackingApplicable=b.trackingApplicable);return c};return b}function m(a,b){0<b.length&&b.forEach(function(b){a[b]=h(b)})}function r(a){void 0===a&&(a=[]);m(M,a);return M}var u=v(c),C=
v(d),F=v(e),A=v(b),D=v(k),z=v(w),G=function(a){return a&&"AjaxError"===a.type},x=function(a,b,c,g){a=C["default"].post(a,{accepts:"text/html, application/json",contentType:"application/json",additionalHeaders:{"x-amz-acp-params":g}},c);a.then(function(){q(b,"success")},function(a){if(G(a)){var c=a.statusCode;"Request Timeout"===a.statusText?q(b,"timeout"):q(b,"error",c)}else"Ajax request aborted"===a&&q(b,"abort")});return F["default"].promise(a.then(function(a){var b=a.contentType;a=a.responseBody;
if("application/json"===b)return a||{};if("text/html"===b)try{var c=(new DOMParser).parseFromString(a,"text/html").querySelector("body").firstElementChild;return D["default"].proxify(c,c)}catch(N){throw Error("Error encountered when parsing html response: "+N);}else throw Error("Unexpected content-type found when parsing response: "+b);}))},q=function(a,b,c){y(A["default"].count,"mix:remoteOperations",b,c);y(z["default"].count,"remoteOperations:"+a,b,c)},y=function(a,b,c,g){"success"===c?a(b+":attempt",
1):(a(b+":attempt",0),a(b+":error:"+(g||c),1))},E=/[-_]$/,H=/^[-_]/,J={hitType:"pageTouch",pageAssemblyType:"main"},K=(c=f.uept)?{"page-type":c.pageType,"sub-page-type":c.subPageType}:{},I=function(){return"Bad data-acp-tracking value."},g,t,l,M={};a.default={setup:r};a.initialize=function(a,b,c){if((a=u["default"].cardRoot)&&a.hasAttribute("data-acp-path")&&a.hasAttribute("data-acp-params")){g=a.getAttribute("data-acp-path")||"";b=a.getAttribute("data-acp-params")||"";try{var d=document.createElement("textarea");
d.innerHTML=b;t=0===d.childNodes.length?"":d.childNodes[0].nodeValue||""}catch(R){throw Error("Issue encountered while parsing card attributes when setting up RemoteOperations, error: "+R);}a.removeAttribute("data-acp-path");a.removeAttribute("data-acp-params")}else throw Error("Remote Operation capability requires card root node to exist and have attribute: data-acp-path \x26 data-acp-params");a:{if(u["default"].cardRoot.hasAttribute("data-acp-tracking"))try{l=JSON.parse(u["default"].cardRoot.getAttribute("data-acp-tracking"));
break a}catch(R){f.P.logError(R,R instanceof SyntaxError?""+I:null,"ERROR")}l=L}c._operationNames&&m(M,c._operationNames)};a.isAjaxError=G;a.setup=r;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/scoped-dom",["exports","tslib","@c/dom"],function(a,c,d){function e(a,b){return a instanceof HTMLElement||a instanceof Node?b&&b.contains(a)||u["default"].scopes.some(function(b){return b.contains(a)})||!document.body.contains(a):!0}function b(a,b){if("undefined"===typeof Proxy||"undefined"===
typeof Reflect)return a;var c=a instanceof HTMLElement||a instanceof Node?h():a instanceof HTMLCollection||a instanceof NodeList?r():a instanceof Event?v():void 0;e(a,b)?c&&(a[E]||(a[E]=new Proxy(a,c)),a=a[E]):a=null;return a}function k(a){return function(){for(var b=[],c=0;c<arguments.length;c++)b[c]=arguments[c];b=b.map(function(a){return"function"===typeof a?w(a):a!==L&&a.__unscope__?d.unscope(a):a});return a.apply(d.unscope(this),b)}}function w(a){return a.__proxy||(a.__proxy=function(){for(var c=
[],d=0;d<arguments.length;d++)c[d]=arguments[d];return a.apply(b(this),c.map(function(a){return b(a)}))})}function p(a){return function(b){if(b===u["default"])return a;throw Error("Unable to unscope event target, password does not match.");}}function v(){return{get:function(a,c){var d=Reflect.get(a,c);if(c===E)return d;var g=Object.getOwnPropertyDescriptor(a,c);return g&&!1===g.configurable&&!1===g.writable?d:"__unscope__"===c?p(a):"function"===typeof d?m(d,a,c):b(d)}}}function h(){return{get:function(a,
c){var d=Reflect.get(a,c);if(c===E)return d;var g=Object.getOwnPropertyDescriptor(a,c);if(g&&!1===g.configurable&&!1===g.writable)return d;if("ownerDocument"===c)return null;if("__unscope__"===c)return p(a);"closest"===c&&(d=F);return"function"===typeof d?m(d,a,c):b(d)},set:function(a,c,d){"string"===typeof c&&c.startsWith("on")&&"function"===typeof d?Reflect.set(a,c,function(a){d.call(b(this),b(a))}):Reflect.set(a,c,d);return!0}}}function m(a,d,e){var g=d[H]=d[H]||{},t=g[e];if(!t){if("addEventListener"===
e){var l=a;a=function(a,b,d){b="handleEvent"in b?c.__assign(c.__assign({},b),{handleEvent:w(b.handleEvent)}):b;return l.call(this,a,b,d)}}t=k(a);g[e]=t}return function(){for(var a=[],c=0;c<arguments.length;c++)a[c]=arguments[c];return b(t.apply(d,a))}}function r(){return{get:function(a,c){var d=Reflect.get(a,c),g=Object.getOwnPropertyDescriptor(a,c);return g&&!1===g.configurable&&!1===g.writable?d:"number"===typeof c||"string"===typeof c&&Number.isInteger(Number.parseInt(c,10))?b(d):"__unscope__"===
c?p(a):d}}}var u=d&&"object"===typeof d&&"default"in d?d:{"default":d};f.mixCardIndex=f.mixCardIndex||0;var C=Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector,F=Element.prototype.closest||function(a){var b=this;do{if(C.call(b,a))return b;b=b.parentNode}while(b);return null},A="body frame frameset head html iframe script style".split(" "),D=function(a){var c=b(a,a);u["default"].scopes.push(a);return{root:c,validate:function(a){return a()},isAccessibleEvent:function(a){return e(a.target,
c)}}},z=function(a){return e.apply(void 0,c.__spread([a.target],u["default"].scopes))},G=function(a){return e.apply(void 0,c.__spread([a],u["default"].scopes))},x=function(a){return a()},q=function(a){if(-1<A.indexOf(a))throw Error("The following element is not allowed to be created in cards: '"+a+"'.");a=document.createElement(a);return b(a)},y={get cardRoot(){return b(u["default"].cardRoot,u["default"].cardRoot)},scopeElement:D,isAccessibleEvent:z,isAccessibleElement:G,validate:x,createElement:q,
proxify:b},E,H;a.cardRoot=function(){return b(u["default"].cardRoot,u["default"].cardRoot)};a.createElement=q;a.default=y;a.initialize=function(a,b,c){a=f.mixCardIndex++;E="__proxified_"+a;H="__wrappedSafeMethods_"+a};a.isAccessibleElement=G;a.isAccessibleEvent=z;a.scopeElement=D;a.validate=x;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/scoped-metrics",["exports","tslib","@c/metrics","@c/dom"],function(a,c,d,e){var b=e&&"object"===typeof e&&"default"in e?e:{"default":e},k=[];e=function(a,
c){void 0===c&&(c="");var d=b["default"].cardRoot.parentElement;d&&d.classList.contains("celwidget")&&(c=(d.getAttribute("cel_widget_id")||d.getAttribute("data-cel-widget")||d.getAttribute("id"))+c,a.setAttribute("cel_widget_id",c),a.setAttribute("data-cel-widget",c),d.classList.contains("c-f")&&a.classList.add("c-f"),a.classList.add("celwidget"))};var f=function(a,b,c){k.forEach(function(e){d.count(e+":"+a,b,c)})},p={count:f,instrumentCel:e};a.count=f;a.default=p;a.initialize=function(a,d,e){if(a=
b["default"].cardRoot.getAttribute("data-card-metrics-id"))a=c.__read(a.split("_",1),1)[0],k.push(a)};a.instrumentCel=e;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/siege",["exports"],function(a){var c=function(a,b){return a.factoryClone({trackingParams:{sif_profile:b},trackingApplicable:!0})},d={applySifProfile:c};a.applySifProfile=c;a.default=d;a.initialize=function(a,b,c){};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/sudo",["exports"],function(a){a.default={get cardRoot(){return null}};
a.initialize=function(a,d,e){};a.sudo={};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/timing",["exports","tslib","@c/dom"],function(a,c,d){var e=d&&"object"===typeof d&&"default"in d?d:{"default":d},b,k;a.CARD_METRICS_ID_KEY="data-card-metrics-id";a.CEL_WIDGET_KEY="cel_widget_id";a.INSTANCE_ID_KEY="id";a.callEventInstance=function(a,b){for(var d=[],e=2;e<arguments.length;e++)d[e-2]=arguments[e];(e=f.mix_csa_event)&&e(a).apply(void 0,c.__spread([b],d))};a.initialize=function(a,c,d){b=
e["default"].cardRoot?e["default"].cardRoot.getAttribute("id"):null;k=e["default"].cardRoot?e["default"].cardRoot.getAttribute("data-card-metrics-id"):null};a.markFunctional=function(){var a=f.mix_csa;a&&k&&a('[cel_widget_id\x3d"'+k+'"]',"#"+b)("mark","functional")};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/tracking",["exports","tslib","@c/dom","@c/logger","@c/remote-operations"],function(a,c,d,e,b){function f(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var w=
f(d),p=f(e),v=f(b),h={missingAcpTrackingValue:function(){return"Missing data-acp-tracking."}},m=function(){if(!w["default"].cardRoot.hasAttribute("data-acp-tracking")){var a=h.missingAcpTrackingValue();p["default"].log(Error(a),"FATAL");return!1}return!0},r=function(a,b,c){void 0===b&&(b={});void 0===c&&(c=!1);return a.factoryClone({trackingParams:b,trackingStandalone:c,trackingApplicable:!0})};d=function(a,b,d){void 0===b&&(b={});var e=v["default"].setup([a]);return m()?r(e[a],c.__assign(c.__assign({},
b),{refSuffix:d}),!0):e[a]};e=function(a,b,d){void 0===b&&(b={});return m()?r(a,c.__assign(c.__assign({},b),{refSuffix:d})):a};b={createTracking:d,addTracking:e};a.addTracking=e;a.createTracking=d;a.default=b;a.initialize=function(a,b,c){};Object.defineProperty(a,"__esModule",{value:!0})});(function(){var a=function(a,b,c){mix_d(a,b,c)};a.amd=!0;var c,d,e,b,f,w,p,v,h,m,r,u,C,F,A,D,z,G,x,q,y,E,H;(function(b){function c(a,b){a!==d&&("function"===typeof Object.create?Object.defineProperty(a,"__esModule",
{value:!0}):a.__esModule=!0);return function(c,d){return a[c]=b?b(c,d):d}}var d="object"===typeof global?global:"object"===typeof self?self:"object"===typeof this?this:{};"function"===typeof a&&a.amd?a("tslib",["exports"],function(a){b(c(d,c(a)))}):"object"===typeof module&&"object"===typeof module.exports?b(c(d,c(module.exports))):b(c(d))})(function(a){var k=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,
c)&&(a[c]=b[c])};c=function(a,b){function c(){this.constructor=a}k(a,b);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)};d=Object.assign||function(a){for(var b,c=1,d=arguments.length;c<d;c++){b=arguments[c];for(var g in b)Object.prototype.hasOwnProperty.call(b,g)&&(a[g]=b[g])}return a};e=function(a,b){var c={},d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&0>b.indexOf(d)&&(c[d]=a[d]);if(null!=a&&"function"===typeof Object.getOwnPropertySymbols){var g=0;for(d=Object.getOwnPropertySymbols(a);g<
d.length;g++)0>b.indexOf(d[g])&&Object.prototype.propertyIsEnumerable.call(a,d[g])&&(c[d[g]]=a[d[g]])}return c};b=function(a,b,c,d){var g=arguments.length,e=3>g?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d,l;if("object"===typeof Reflect&&"function"===typeof Reflect.decorate)e=Reflect.decorate(a,b,c,d);else for(var n=a.length-1;0<=n;n--)if(l=a[n])e=(3>g?l(e):3<g?l(b,c,e):l(b,c))||e;return 3<g&&e&&Object.defineProperty(b,c,e),e};f=function(a,b){return function(c,d){b(c,d,a)}};w=function(a,b){if("object"===
typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(a,b)};p=function(a,b,c,d){function g(a){return a instanceof c?a:new c(function(b){b(a)})}return new (c||(c=Promise))(function(c,e){function n(a){try{t(d.next(a))}catch(N){e(N)}}function l(a){try{t(d["throw"](a))}catch(N){e(N)}}function t(a){a.done?c(a.value):g(a.value).then(n,l)}t((d=d.apply(a,b||[])).next())})};v=function(a,b){function c(a){return function(b){return d([a,b])}}function d(c){if(e)throw new TypeError("Generator is already executing.");
for(;g;)try{if(e=1,t&&(n=c[0]&2?t["return"]:c[0]?t["throw"]||((n=t["return"])&&n.call(t),0):t.next)&&!(n=n.call(t,c[1])).done)return n;if(t=0,n)c=[c[0]&2,n.value];switch(c[0]){case 0:case 1:n=c;break;case 4:return g.label++,{value:c[1],done:!1};case 5:g.label++;t=c[1];c=[0];continue;case 7:c=g.ops.pop();g.trys.pop();continue;default:if(!(n=g.trys,n=0<n.length&&n[n.length-1])&&(6===c[0]||2===c[0])){g=0;continue}if(3===c[0]&&(!n||c[1]>n[0]&&c[1]<n[3]))g.label=c[1];else if(6===c[0]&&g.label<n[1])g.label=
n[1],n=c;else if(n&&g.label<n[2])g.label=n[2],g.ops.push(c);else{n[2]&&g.ops.pop();g.trys.pop();continue}}c=b.call(a,g)}catch(T){c=[6,T],t=0}finally{e=n=0}if(c[0]&5)throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}var g={label:0,sent:function(){if(n[0]&1)throw n[1];return n[1]},trys:[],ops:[]},e,t,n,q;return q={next:c(0),"throw":c(1),"return":c(2)},"function"===typeof Symbol&&(q[Symbol.iterator]=function(){return this}),q};h=function(a,b){for(var c in a)"default"===c||Object.prototype.hasOwnProperty.call(b,
c)||H(b,a,c)};H=Object.create?function(a,b,c,d){d===L&&(d=c);Object.defineProperty(a,d,{enumerable:!0,get:function(){return b[c]}})}:function(a,b,c,d){d===L&&(d=c);a[d]=b[c]};m=function(a){var b="function"===typeof Symbol&&Symbol.iterator,c=b&&a[b],d=0;if(c)return c.call(a);if(a&&"number"===typeof a.length)return{next:function(){a&&d>=a.length&&(a=void 0);return{value:a&&a[d++],done:!a}}};throw new TypeError(b?"Object is not iterable.":"Symbol.iterator is not defined.");};r=function(a,b){var c="function"===
typeof Symbol&&a[Symbol.iterator];if(!c)return a;a=c.call(a);var d,e=[];try{for(;(void 0===b||0<b--)&&!(d=a.next()).done;)e.push(d.value)}catch(P){var g={error:P}}finally{try{d&&!d.done&&(c=a["return"])&&c.call(a)}finally{if(g)throw g.error;}}return e};u=function(){for(var a=[],b=0;b<arguments.length;b++)a=a.concat(r(arguments[b]));return a};C=function(){for(var a=0,b=0,c=arguments.length;b<c;b++)a+=arguments[b].length;a=Array(a);var d=0;for(b=0;b<c;b++)for(var e=arguments[b],q=0,f=e.length;q<f;q++,
d++)a[d]=e[q];return a};F=function(a){return this instanceof F?(this.v=a,this):new F(a)};A=function(a,b,c){function d(a){f[a]&&(l[a]=function(b){return new Promise(function(c,d){1<t.push([a,b,c,d])||e(a,b)})})}function e(a,b){try{var c=f[a](b);c.value instanceof F?Promise.resolve(c.value.v).then(g,q):n(t[0][2],c)}catch(U){n(t[0][3],U)}}function g(a){e("next",a)}function q(a){e("throw",a)}function n(a,b){(a(b),t.shift(),t.length)&&e(t[0][0],t[0][1])}if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");
var f=c.apply(a,b||[]),l,t=[];return l={},d("next"),d("throw"),d("return"),l[Symbol.asyncIterator]=function(){return this},l};D=function(a){function b(b,e){c[b]=a[b]?function(c){return(d=!d)?{value:F(a[b](c)),done:"return"===b}:e?e(c):c}:e}var c,d;return c={},b("next"),b("throw",function(a){throw a;}),b("return"),c[Symbol.iterator]=function(){return this},c};z=function(a){function b(b){e[b]=a[b]&&function(d){return new Promise(function(e,g){d=a[b](d);c(e,g,d.done,d.value)})}}function c(a,b,c,d){Promise.resolve(d).then(function(b){a({value:b,
done:c})},b)}if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var d=a[Symbol.asyncIterator],e;return d?d.call(a):(a="function"===typeof m?m(a):a[Symbol.iterator](),e={},b("next"),b("throw"),b("return"),e[Symbol.asyncIterator]=function(){return this},e)};G=function(a,b){Object.defineProperty?Object.defineProperty(a,"raw",{value:b}):a.raw=b;return a};var I=Object.create?function(a,b){Object.defineProperty(a,"default",{enumerable:!0,value:b})}:function(a,b){a["default"]=
b};x=function(a){if(a&&a.__esModule)return a;var b={};if(null!=a)for(var c in a)"default"!==c&&Object.prototype.hasOwnProperty.call(a,c)&&H(b,a,c);I(b,a);return b};q=function(a){return a&&a.__esModule?a:{"default":a}};y=function(a,b){if(!b.has(a))throw new TypeError("attempted to get private field on non-instance");return b.get(a)};E=function(a,b,c){if(!b.has(a))throw new TypeError("attempted to set private field on non-instance");b.set(a,c);return c};a("__extends",c);a("__assign",d);a("__rest",e);
a("__decorate",b);a("__param",f);a("__metadata",w);a("__awaiter",p);a("__generator",v);a("__exportStar",h);a("__createBinding",H);a("__values",m);a("__read",r);a("__spread",u);a("__spreadArrays",C);a("__await",F);a("__asyncGenerator",A);a("__asyncDelegator",D);a("__asyncValues",z);a("__makeTemplateObject",G);a("__importStar",x);a("__importDefault",q);a("__classPrivateFieldGet",y);a("__classPrivateFieldSet",E)})})();mix_d("@c/aui-bottom-sheet","exports tslib @c/logger @c/api-lock @c/dom @c/scoped-dom @p/a-events @p/A @p/a-sheet @c/guard @c/scoped-metrics".split(" "),
function(a,c,d,e,b,k,w,p,v,h,m){function r(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function u(){}function C(a,d,e){var q=this;void 0===e&&(e={});var g=D["default"].cardRoot.querySelector(d);d="@amzn/mix.client-cap.aui-bottom-sheet: Failed to call 'create' on bottom-sheet '"+a+"'.";if(!g)throw Error(d+" A root element is required. Cannot find a matched element by the given selector");if("function"===typeof getComputedStyle&&"none"!==getComputedStyle(b.unscope(g)).display)throw Error(d+
" The sheet DOM root should be hidden initially. DOM root should use the AUI '.aok-hidden' class");var f=a+"-"+J;if(x["default"].get(f))throw Error(d+" The sheet name '"+a+"' has already been used in this card. Choose a different one.");g.setAttribute("id",f);var k=x["default"].create(c.__assign(c.__assign({closeType:"icon"},e),{historySupportEnabled:!1,preloadDomId:g.id,name:f}));z["default"].one("a:sheet:beforeShow:"+f,function(){m.instrumentCel(b.unscope(g),"bottom-sheet-"+a)});var h=D["default"].scopeElement(b.unscope(g)).root,
y=k._height;return E({getHeight:function(){return y},changeHeight:function(a){return new Promise(function(b){var c=function(){y=k._height;b(!0)};z["default"].one("a:sheet:changeHeight:"+f,c);k.changeHeight({height:a})||(z["default"].off("a:sheet:changeHeight:"+f,c),b(!1))})},show:function(){return A["default"].isLockedFor(["click"])?(F["default"].log("Failed to call show because no click event was detected","FATAL"),Promise.resolve(!1)):new Promise(function(b){var c=function(){b(!0)};z["default"].one("a:sheet:afterShow:"+
f,c);x["default"].showSheet(k)?m.count("bottomSheet:"+a+":show",1):(z["default"].off("a:sheet:afterShow:"+f,c),m.count("bottomSheet:"+a+":show",0),b(!1))})},hide:function(){return A["default"].isLockedFor(["click"])?(F["default"].log("Failed to call hide because no click event was detected","FATAL"),Promise.resolve(!1)):new Promise(function(b){var c=function(){b(!0)};z["default"].one("a:sheet:afterHide:"+f,c);x["default"].hideSheet(k)?m.count("bottomSheet:"+a+":hide",1):(z["default"].off("a:sheet:afterHide:"+
f,c),m.count("bottomSheet:"+a+":hide",0),b(!1))})},render:function(a){return c.__awaiter(q,void 0,void 0,function(){var b,d,e=this;return c.__generator(this,function(n){switch(n.label){case 0:if(!k._animating)return[3,2];b=["a:sheet:afterShow:"+f,"a:sheet:afterHide:"+f,"a:sheet:changeHeight:"+f];return[4,new Promise(function(a){d=function(){a()};b.forEach(function(a){z["default"].one(a,d)})})];case 1:n.sent(),b.forEach(function(a){z["default"].off(a,d)}),n.label=2;case 2:return[2,new Promise(function(b){G["default"].requestAnimationFrame(function(){return c.__awaiter(e,
void 0,void 0,function(){return c.__generator(this,function(c){switch(c.label){case 0:return[4,a(h)];case 1:return c.sent(),b(),[2]}})})})})]}})})}},{beforeShow:"a:sheet:beforeShow:"+f,afterShow:"a:sheet:afterShow:"+f,beforeHide:"a:sheet:beforeHide:"+f,afterHide:"a:sheet:afterHide:"+f},u)}var F=r(d),A=r(e),D=r(k),z=r(w),G=r(p),x=r(v),q=r(h),y=function(a,b,c){return a.__wrapHandler?a.__wrapHandler:a.__wrapHandler=function(d){d=q["default"].current(a)(c?c(d,b):d);d instanceof Promise&&q["default"].promise(d)}},
E=function(a,b,d){return c.__assign(c.__assign({},a),{on:function(a,c){c=y(c,a,d);z["default"].on(b[a],c)},off:function(a,c){c=c.__wrapHandler;if(!c)throw Error("Unknown event handler!");z["default"].off(b[a],c)},once:function(a,c){c=y(c,a,d);z["default"].one(b[a],c)}})};f.mixCardIndex=f.mixCardIndex||0;var H;(function(a){a[a.Success=1]="Success";a[a.Failure=0]="Failure"})(H||(H={}));var J;d={create:C};a.create=C;a.default=d;a.initialize=function(a,b,c){J=f.mixCardIndex++};Object.defineProperty(a,
"__esModule",{value:!0})});mix_d("@c/aui-card",["exports","@p/a-cardui","@p/a-cardui-deck","@c/dom"],function(a,c,d,e){function b(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function f(a){var b=p["default"].get(e.unscope(a));return{isExpanded:function(){return b.isExpanded()},toggle:function(){return b.toggle()}}}function w(a){var b=v["default"].get(e.unscope(a));return{initializeAllCards:function(){return b.initializeAllCards()}}}var p=b(c),v=b(d);a.default={getCard:f,getCardDeck:w};
a.getCard=f;a.getCardDeck=w;a.initialize=function(a,b,c){};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-carousel","exports tslib @c/dom @p/a-carousel-framework @p/A @p/a-events @c/guard".split(" "),function(a,c,d,e,b,k,w){function p(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function v(a,b){return"change:pageNumber"===b?{newPageNumber:a.newValue,oldPageNumber:a.oldValue}:{}}function h(a,b){var e=this,f=b.strategies.display.repaint;return function(q,k){return c.__awaiter(e,
void 0,void 0,function(){var e,h,g,y,m;return c.__generator(this,function(c){switch(c.label){case 0:return[4,a({indexes:q,ids:k})];case 1:e=c.sent();"string"===typeof e&&(e=(new DOMParser).parseFromString(e,"text/html").body.children[0]);if(!e.classList.contains("a-carousel-content-fragment"))throw Error("CarouselRemoteOperation did not return a ContentFragment");h=Array.prototype.slice.call(e.querySelectorAll(".a-carousel-card-fragment")).map(function(a){return a.hasAttribute("data-a-delete")?null:
d.unscope(a)});g=b.getAttr("ajax");if(g.id_list&&k&&(y=q.filter(function(a,b){return null===h[b]}),y.length)){for(m=y.length-1;0<=m;m--)g.id_list.splice(y[m],1);b.setAttr("ajax",g);f&&u["default"].requestAnimationFrame(function(){f(b)})}return[2,h]}})})}}function m(a){var b=a.getAttr("name")||a.__id;if(0===b.indexOf("ciid"))return b;b="ciid-"+z+"-"+G+"-"+b;a.setAttr("name",b);return b}var r=p(e),u=p(b),C=p(k),F=p(w),A=function(a,b,c){return a.__wrapHandler?a.__wrapHandler:a.__wrapHandler=function(d){d=
F["default"].current(a)(c?c(d,b):d);d instanceof Promise&&F["default"].promise(d)}},D=function(a,b,d){return c.__assign(c.__assign({},a),{on:function(a,c){c=A(c,a,d);C["default"].on(b[a],c)},off:function(a,c){c=c.__wrapHandler;if(!c)throw Error("Unknown event handler!");C["default"].off(b[a],c)},once:function(a,c){c=A(c,a,d);C["default"].one(b[a],c)}})};f.mixCardIndex=f.mixCardIndex||0;var z,G;a.default={getCarousel:function(a){var b=r["default"].getCarousel(d.unscope(a)),c=m(b);return D({gotoPage:function(a){return b.gotoPage(a)},
gotoPrevPage:function(){return b.gotoPrevPage()},gotoNextPage:function(){return b.gotoNextPage()},get initialized(){return new Promise(function(a){return r["default"].onInit(c,function(){return a()})})},attachRemoteOperation:function(a){if(b.getAttr("async_provider"))throw Error("Carousel already has attached remoteOperation");b.setAttr("async_provider",h(a,b))}},{"change:pageNumber":"a:carousel:"+c+":change:pageNumber","change:fetchedItems":"a:carousel:"+c+":change:fetchedItems"},v)}};a.initialize=
function(a,b,c){z="#"===a[0]?a.slice(1):a;G=f.mixCardIndex++};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-feature-detect",["exports","@p/A"],function(a,c){var d=c&&"object"===typeof c&&"default"in c?c:{"default":c};c=function(a){return d["default"].capabilities[a]};a.default={isSupported:c};a.initialize=function(a,b,c){};a.isSupported=c;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-modal","exports tslib @p/a-modal @p/a-events @c/dom @c/scoped-dom @c/logger @c/scoped-metrics @c/aui-feature-detect @c/guard @c/api-lock".split(" "),
function(a,c,d,e,b,k,w,p,v,h,m){function r(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function u(){f.mixActiveModal=""}function C(a){if(""===f.mixActiveModal)f.mixActiveModal=a,y["default"].one("a:popover:invisible:"+a,u);else if(f.mixActiveModal!==a)throw Error(l.modalInUsed(f.mixActiveModal));}function F(){}function A(a){return a?a.substring(0,a.lastIndexOf("-"+M)):""}function D(a){return{beforeShow:"a:popover:beforeShow:"+a,afterShow:"a:popover:visible:"+a,beforeHide:"a:popover:beforeHide:"+
a,afterHide:"a:popover:invisible:"+a}}function z(a){return new Promise(function(b,c){f.P.when("a-popover-animate").execute(function(d){try{b(d.isAnimating(a))}catch(N){c(N)}})})}function G(a,d,e){var g=this;y["default"].one("a:popover:beforeShow:"+a,function(){p.instrumentCel(b.unscope(e),"modal-"+a)});var k=E["default"].scopeElement(b.unscope(e)).root;return t({id:a,show:function(){return c.__awaiter(g,void 0,void 0,function(){return c.__generator(this,function(b){return I["default"].isLockedFor(P)?
(H["default"].log(l.failToCallFor("show",A(a))+"  "+l.missingUserInteraction(P),"FATAL"),[2,Promise.resolve(!1)]):[2,new Promise(function(b){var c=function(){p.count("modal:"+A(a)+":show",1);b(!0)};y["default"].one(D(a).afterShow,c);try{C(a),d.show()}catch(Q){H["default"].log(l.failToCallFor("show",A(a))+" "+Q.message,"FATAL"),Q.message!==l.modalInUsed(f.mixActiveModal)&&f.mixActiveModal===a&&(y["default"].off("a:popover:invisible:"+a,u),u()),y["default"].off(D(a).afterShow,c),p.count("modal:"+A(a)+
":show",0),b(!1)}})]})})},hide:function(){return c.__awaiter(g,void 0,void 0,function(){return c.__generator(this,function(b){return I["default"].isLockedFor(P)?(H["default"].log(l.failToCallFor("hide",A(a))+"  "+l.missingUserInteraction(P),"FATAL"),[2,Promise.resolve(!1)]):[2,new Promise(function(b){var c=function(){b(!0)};y["default"].one(D(a).afterHide,c);try{d.hide()}catch(Q){H["default"].log(l.failToCallFor("hide",A(a))+" "+Q.message,"FATAL"),y["default"].off(D(a).afterHide,c),b(!1)}})]})})},
render:function(b){return c.__awaiter(g,void 0,void 0,function(){var e;return c.__generator(this,function(c){e=function(){return new Promise(function(c,e){try{b(k),d.isActive()&&d.updatePosition()}catch(S){H["default"].log(l.failToCallFor("render",A(a))+" "+S.message,"FATAL"),e(S)}c()})};return[2,z(d).then(function(b){if(!b)return e();var c=d.isActive()?D(a).afterShow:D(a).afterHide;return new Promise(function(a){y["default"].one(c,function(){a(e())})})})]})})}},D(a),F)}function x(a,d,e){d=E["default"].cardRoot.querySelector(d);
var f=l.failToCallFor("create",a);if(J["default"].isSupported("mobile"))throw Error(f+" "+l.unsupportedDevice("mobile"));if(!a)throw Error(f+" "+l.invalidName(a));if(q["default"].get(a+"-"+M))throw Error(f+" "+l.usedName(a));if(!d)throw Error(f+" "+l.unavailableRoot());if(A(d.getAttribute("data-a-modal-id")))throw Error(f+" "+l.usedRootOf(A(d.getAttribute("data-a-modal-id"))));if(!d.className.match(O))throw Error(f+" "+l.leakedRoot());var g=document.createElement("span");f=a+"-"+M;e=c.__assign(c.__assign({name:f,
popoverLabel:e.a11yOpenMessage,hideHeader:!0,closeButton:e.closeButton===L?!0:e.closeButton,padding:"none",legacyNavigable:!1},e.width?{width:e.width+"px"}:{}),e.height?{height:e.height+"px"}:{});e=q["default"].create(g,e);f=G(f,e,d);try{var k=e.attrs("name"),n=b.unscope(d),h=document.createElement("span");E["default"].cardRoot.appendChild(h);h.id="a-popover-"+k;h.className="a-popover-preload";h.appendChild(n);d.setAttribute("data-a-modal-id",k);d.className=d.className.replace(O,"")}catch(Q){throw Error(l.failToCallFor("create",
a)+" "+Q.message);}return f}var q=r(d),y=r(e),E=r(k),H=r(w),J=r(v),K=r(h),I=r(m),g=function(a,b,c){return a.__wrapHandler?a.__wrapHandler:a.__wrapHandler=function(d){d=K["default"].current(a)(c?c(d,b):d);d instanceof Promise&&K["default"].promise(d)}},t=function(a,b,d){return c.__assign(c.__assign({},a),{on:function(a,c){c=g(c,a,d);y["default"].on(b[a],c)},off:function(a,c){c=c.__wrapHandler;if(!c)throw Error("Unknown event handler!");y["default"].off(b[a],c)},once:function(a,c){c=g(c,a,d);y["default"].one(b[a],
c)}})},l={failToCallFor:function(a,b){return"@amzn/mix.client-cap.aui-modal: Failed to call '"+a+"' on modal '"+b+"'."},usedName:function(a){return"The modal name '"+a+"' has already been used in this card. Choose a different one."},unavailableRoot:function(){return"A root element is required. Cannot find a matched element by the given selector."},leakedRoot:function(){return"The modal DOM root should be hidden initially. DOM root should use the AUI '.aok-hidden' class."},usedRootOf:function(a){return"The root has already been bound to another modal, '"+
a+"'. Choose a different one."},invalidName:function(a){return"The modal name is invalid: "+a+"."},modalInUsed:function(a){return"Modal '"+a+"' is in use and should not be interrupted."},unsupportedDevice:function(a){return"Modal is only supported in desktop. Your card is in a "+a+" context."},missingUserInteraction:function(a){return"This operation can be only performed upon a user interaction of: "+a+". Browser Operation is the only recommended way over native event APIs."}};f.mixActiveModal=f.mixActiveModal||
"";f.mixCardIndex=f.mixCardIndex||0;var M,B;(function(a){a[a.Success=1]="Success";a[a.Failure=0]="Failure"})(B||(B={}));var O=/\baok-hidden\b/g,P=["click"];d={create:x};a.create=x;a.default=d;a.initialize=function(a,b,c){M=f.mixCardIndex++};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/aui-truncate",["exports","@c/dom","@p/a-truncate"],function(a,c,d){function e(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function b(a){return h["default"].manualTruncate(a)}function f(){return h["default"].refreshAutoTruncate()}
function w(a){return h["default"].switchToAutoTruncate(a)}function p(){var a=v["default"].cardRoot.getElementsByClassName("a-truncate");Array.prototype.slice.call(a).forEach(function(a){return h["default"].get(c.unscope(a)).update()})}var v=e(c),h=e(d);a.default={manualTruncate:b,refreshAutoTruncate:f,switchToAutoTruncate:w,updateAll:p};a.initialize=function(a,b,c){};a.manualTruncate=b;a.refreshAutoTruncate=f;a.switchToAutoTruncate=w;a.updateAll=p;Object.defineProperty(a,"__esModule",{value:!0})});
mix_d("@c/aui-utils",["exports","@p/A","@c/dom"],function(a,c,d){function e(a){if(null===a||a===L)throw new TypeError("Value is null or undefined");}function b(a){x["default"].hide(d.unscope(a))}function f(a){x["default"].show(d.unscope(a))}function w(a){return x["default"].loadDynamicImage(d.unscope(a))}function p(a,b){return x["default"].onScreen(d.unscope(a),b)}function v(a){return x["default"].objectIsEmpty(a)}function h(a,b){return x["default"].equals(a,b)}function m(a,b){return x["default"].diff(a,
b)}function r(a,b,c){return x["default"].throttle(a,b,c)}function u(a,b,c){return x["default"].debounce(a,b,c)}function C(a){x["default"].defer(a)}function F(a,b){return x["default"].interval(a,b)}function A(a){return x["default"].animationFrameDelay(a)}function D(a,b){return x["default"].delay(a,b)}function z(a){return x["default"].once(a)}function G(a){return x["default"].attributionChain(d.unscope(a))}var x=c&&"object"===typeof c&&"default"in c?c:{"default":c};c={assertNotNullish:e,hide:b,show:f,
loadDynamicImage:w,onScreen:p,objectIsEmpty:v,equals:h,diff:m,throttle:r,debounce:u,defer:C,interval:F,animationFrameDelay:A,delay:D,once:z,attributionChain:G};a.animationFrameDelay=A;a.assertNotNullish=e;a.attributionChain=G;a.debounce=u;a.default=c;a.defer=C;a.delay=D;a.diff=m;a.equals=h;a.hide=b;a.initialize=function(a,b,c){};a.interval=F;a.loadDynamicImage=w;a.objectIsEmpty=v;a.onScreen=p;a.once=z;a.show=f;a.throttle=r;Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/error-handling",
["exports"],function(a){var c,d=function(a,b,d,f){c.error(a,b,d,f)};a.default={error:d};a.error=d;a.initialize=function(a,b,d,f){c=f};Object.defineProperty(a,"__esModule",{value:!0})});mix_d("@c/pagemarker",["exports","@p/A","@c/dom","@c/guard"],function(a,c,d,e){function b(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}function f(a){var b;return function(){return h["default"].promise(b=b||new Promise(function(b){return p["default"].on(a,function(){return b()})}))}}function w(a){void 0===
a&&(a=0);var b,c=new Promise(function(a){return b=a}),d=function(){p["default"].onScreen(v["default"].container,a)&&(p["default"].off("scroll resize ready",d),b())};p["default"].on("scroll resize ready",d);d();return c}var p=b(c),v=b(d),h=b(e),m=f("ready"),r=f("load");a.default={get pageReady(){return m()},get pageLoad(){return r()},visible:w};a.initialize=function(a,b,c){};a.pageLoad=function(){return r()};a.pageReady=function(){return m()};a.visible=w;Object.defineProperty(a,"__esModule",{value:!0})});
mix_d("@m/mash",["exports","@p/mash"],function(a,c){var d=c&&"object"===typeof c&&"default"in c?c:{"default":c},e;(function(a){a[a.DONE=0]="DONE";a[a.CANCEL=1]="CANCEL";a[a.SAVE=3]="SAVE";a[a.CLOSE=24]="CLOSE"})(e||(e={}));a.addEventListener=function(a,c){d["default"].addEventListener(a,c)};a.addition=function(a,c){console.log("Executing addition api in MASH client capability ");return a+c};a.androidUtil={callCallback:function(a,c,e){d["default"].android_util.callCallback(a,c,e)},removeCallback:function(a){d["default"].android_util.removeCallback(a)},
storeCallback:function(a,c){return d["default"].android_util.storeCallback(a,c)}};a.canLaunchIntentURL=function(a){d["default"].canLaunchIntentURL(a)};a.cancelFullscreen=function(a){d["default"].cancelFullscreen(a)};a.cart={didUpdate:function(a){d["default"].cart.didUpdate(a)}};a.dispatchEvent=function(a){d["default"].dispatchEvent(a)};a.exitEmbeddedBrowser=function(a){d["default"].exitEmbeddedBrowser(a)};a.goBack=function(a){d["default"].goBack(a)};a.initialize=function(a,c,d){};a.interactionMetrics=
{getRealClickTime:function(a){return d["default"].interactionMetrics.getRealClickTime(a)},send:function(a){return d["default"].interactionMetrics.send(a)}};a.iosUtil={callCallback:function(a,c,e){d["default"].ios_util.callCallback(a,c,e)},removeCallback:function(a){d["default"].ios_util.removeCallback(a)},storeCallback:function(a,c){return d["default"].ios_util.storeCallback(a,c)}};a.launchIntentURL=function(a){d["default"].launchIntentURL(a)};a.navigate=function(a){d["default"].navigate(a)};a.navstack=
{begin:function(){return d["default"].navstack.begin()},setBookmark:function(a){d["default"].navstack.setBookmark(a)},clearHistory:function(a){d["default"].navstack.clearHistory(a)},pageIsReadyToDisplay:function(a){d["default"].navstack.pageIsReadyToDisplay(a)}};a.openInExternalBrowser=function(a){d["default"].openInExternalBrowser(a)};a.permissions={requireForFeature:function(a){return d["default"].permissions.requireForFeature(a)},audit_execute:function(){d["default"].permissions.audit.execute()}};
a.privateAPI={getPushNotificationInfo:function(a){d["default"].privateAPI.getPushNotificationInfo(a)}};a.removeEventListener=function(a,c){d["default"].removeEventListener(a,c)};a.requestFullscreen=function(a){d["default"].requestFullscreen(a)};a.share=function(a){d["default"].share(a)};a.showAlert=function(a){d["default"].showAlert(a)};a.showContactPicker=function(a){d["default"].showContactPicker(a)};a.showEmbeddedBrowser=function(a){d["default"].showEmbeddedBrowser(a)};a.showImageGallery=function(a){d["default"].showImageGallery(a)};
a.showLoginDialog=function(a){d["default"].showLoginDialog(a)};Object.defineProperty(a,"__esModule",{value:!0})})});